Add instructions for debug toasts
liftoffio/LiftoffAds-Android pull request #7
Opened 2021-09-21 21:37 UTC by anton-kapralov

2021-09-21 22:58 UTC, zdyn requested changes
This functionality isn't available yet, right? IIUC, we need to release a patch update and mention that this feature requires v1.3.1.

2021-09-21 22:58 UTC, zdyn commented on README.md
> +#### Debugging failures
FYI, we have a "Troubleshooting" section that would be a better section for this.

2021-09-21 22:58 UTC, zdyn commented on README.md
> +order to see those toasts with error messages you need the following:
Slightly less awkward phrasing:
```suggestion
You can observe the reason for an ad load failure as a toast message.
To enable toast messages, turn on debug mode:
```

2021-09-21 22:58 UTC, zdyn commented on README.md
> +// Or set the field directly if you use self-mediated setup.
```suggestion
// Or set the field directly if you use a self-mediated setup.
```

2021-09-21 23:13 UTC, anton-kapralov commented
Thanks!

Yes, added "Requires v1.3.1+." at the beginning of the section.

2021-09-21 23:15 UTC, zdyn approved these changes

2021-09-22 00:08 UTC, anton-kapralov commented
Thanks!

2021-09-22 00:29 UTC, merged